### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Erkigmo** [DeadMG/puppy-se-arcopoles#1]
![image](https://github.com/DeadMG/puppy-se-arcopoles/assets/122825731/c72df417-8239-4395-b676-05525edd72b6)
[factorio-current.log](https://github.com/DeadMG/puppy-se-arcopoles/files/12324387/factorio-current.log)

**Comment by Vektor-537** [comment]
Мод Puppy's SE Arcopoles (0.1.0) вызвал неустранимую ошибку.
Пожалуйста, сообщите об этой ошибке автору мода.

Error while running event puppy-se-arcopoles::on_nth_tick(12)
__puppy-se-arcopoles__/control.lua:62: bad argument #1 of 2 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	__puppy-se-arcopoles__/control.lua:62: in function 'filter'
	__puppy-se-arcopoles__/control.lua:17: in function <__puppy-se-arcopoles__/control.lua:13>

**Comment by DeadMG** [comment]
This should now be fixed.
